### ISSUE TITLE
encoding error on PC

### ISSUE THREAD

**Issue by buffavaholic** [OpenTrons/robot_frontend_v2#2]
Line 55 in main.py 

`open(str(path))`

needs encoding specified

`open(str(path), encoding='utf8')`

At least on PC it does

**Comment by SimplyAhmazing** [comment]
Thanks @buffavaholic for reporting this issue and triple thanks for providing a solution. I've implemented your fix here:

https://github.com/OpenTrons/robot_frontend_v2/blob/20160901-150000-pyinstaller-setup/server/helpers.py#L29

Cheers
